---

  - name: Install NGINX common packages
    apt: pkg={{ item }} state=installed update-cache=yes
    with_items: "{{ nginx_common }}"
    when: production
    become: true

  - name: Install NGINX from scratch
    raw: |
      curl --output {{tmp_dir}}/{{nginx}}.tar.gz --url http://nginx.org/download/{{nginx}}.tar.gz &&
      wget https://github.com/vkholodkov/nginx-upload-module/archive/{{upload_module_zip}} -O {{tmp_dir}}/{{upload_module_zip}} &&
      tar -zxvf {{tmp_dir}}/{{nginx}}.tar.gz -C {{tmp_dir}} &&
      unzip -o {{tmp_dir}}/{{upload_module_zip}} -d {{tmp_dir}} &&
      cd {{tmp_dir}}/{{nginx}} &&
      ./configure --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --pid-path=/run/nginx.pid \
      --add-module={{tmp_dir}}/{{upload_modul_dir}} \
      --with-http_ssl_module \
      --with-http_gzip_static_module \
      --with-http_stub_status_module \
      --with-cc-opt='-Wno-error' &&
      make && make install
    when: production
    become: true

  - name: Install NGINX production configuration file.
    template: src=nginx.conf.prod.j2 dest=/etc/nginx/nginx.conf
    when: production
    notify: restart nginx
    become: true

  - name: Install NGINX required system packages
    apt: pkg={{ item }} state=installed update-cache=yes
    with_items: "{{ nginx_packages }}"
    when: not production
    become: true

  - name: Install NGINX configuration file.
    template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
    notify: restart nginx
    when: not production
    become: true


### NOTES ###
#
# NGINX install options:
# https://www.nginx.com/resources/wiki/start/topics/tutorials/installoptions/
